apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-calculator
  labels:
    app: grpc-calculator
spec:
  scaleTargetRef:
    kind: Deployment
    name: grpc-calculator
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: "Utilization"
        averageUtilization: 50
