apiVersion: v1
kind: Service
metadata:
  name: grpc-calculator
  labels:
    app: grpc-calculator
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 50051
  selector:
    app: grpc-calculator
  type: ClusterIP
