name: Deploy to GCE

on:
  workflow_dispatch:
    inputs:
      external_ip:
        description: "External IP Address"
        default: "0.0.0.0"

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  SSH_USER: ${{secrets.SSH_USER}}
  SSH_KEY: ${{secrets.SSH_KEY}}
  SSH_IP: ${{ github.event.inputs.external_ip }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current repo name
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: Add IP to known_host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $SSH_IP >> ~/.ssh/known_hosts
      - name: Add ssh private key
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "$SSH_KEY"
          echo "$SSH_KEY" > ~/.ssh/id_gcp
          chmod 0600 ~/.ssh/id_gcp
      - name: Stop existing containers
        run: ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "docker ps -q --filter 'name=$REPO_NAME' | xargs -r docker stop"
      - name: Remove existing containers
        run: ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "docker ps -q --filter 'name=$REPO_NAME' | xargs -r docker rm"
      - name: Pull latest image
        run: |
          ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "docker pull $DOCKER_USER/$REPO_NAME:latest"
      - name: Run new container
        run: ssh -i ~/.ssh/id_gcp $SSH_USER@$SSH_IP "docker run -d --restart unless-stopped -p 80:50051 --name $REPO_NAME $DOCKER_USER/$REPO_NAME:latest"
