name: Deploy to GCE

on:
  workflow_dispatch:
    inputs:
      external_ip:
        description: "External IP Address"
        default: "0.0.0.0"

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  SSH_USER: ${{secrets.SSH_USER}}
  SSH_KEY: ${{secrets.SSH_KEY}}
  SSH_IP: ${{ github.event.inputs.external_ip }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current repo name
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: Add IP to known_host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $SSH_IP >> ~/.ssh/known_hosts
      - name: Add ssh private key
        run: |
          eval $(ssh-agent)
          ssh-add - <<< "$SSH_KEY"
      - name: TEST SSH
        run: ssh $SSH_USER@$SSH_IP pwd
      - name: Stop existing containers
        run: ssh $SSH_USER:$SSH_IP docker ps -q --filter "name=$REPO_NAME" | xargs -r docker stop
      - name: Remove existing containers
        run: docker ps -q --filter "name=$REPO_NAME" | xargs -r docker rm
      - name: Pull latest image
        run: docker pull $DOCKER_USER/$REPO_NAME:latest
      - name: Run new container
        run: docker run -d --restart unless-stoped -p 80:50051 --name $REPO_NAME $DOCKER_USER/$REPO_NAME:latest
