name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get current repo name
      run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
    - name: Build docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:latest
    - name: Docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Push docker image to hub
      run: docker push $DOCKER_USER/$REPO_NAME:latest
